import Link from "next/link";
import { ArrowUpRight, Check, LockKeyhole } from "lucide-react";
import { ConnectionNotice, InvoiceList } from "@/components/receivable-card";
import { Evidence } from "@/components/evidence";
export default function Home() {
  return <><section className="hero"><div><span className="tag">Built for the work you’ve already done</span><h1>Your invoice.<br />Your next move.</h1><p>Turn approved invoices into working capital. Get paid in USDG today, while your buyer keeps their payment terms.</p><div className="actions"><Link href="/supplier" className="button">Finance an invoice <ArrowUpRight size={17} /></Link><Link href="/market" className="button secondary">Explore opportunities</Link></div><p className="hero-note">One invoice. One funder. Every step on Arbitrum.</p></div>
    <div className="hero-visual"><img src="/receiva-flow.png" alt="Invoice moving through approval, funding and settlement" /><div className="visual-caption"><LockKeyhole size={15} />Private invoice file. Public settlement proof.</div></div>
  </section><section><div className="section-heading"><h2>From approved to paid.</h2><Link href="/buyer">Go to buyer desk</Link></div><div className="process"><div className="process-item"><span className="step">1</span><div><h3>Buyer approves</h3><p>Confirms the invoice and posts a partial bond.</p></div></div><div className="process-item"><span className="step">2</span><div><h3>Funder advances</h3><p>The supplier receives the agreed USDG amount.</p></div></div><div className="process-item"><span className="step">3</span><div><h3>Buyer settles</h3><p>The funder is paid and an on-time buyer gets their bond back.</p></div></div></div></section>
  <section><div className="section-heading"><h2>The invoice ledger</h2><span className="subtle"><Check size={14} style={{ display: "inline", marginRight: 5 }} />Read directly from the contract</span></div><ConnectionNotice /><InvoiceList /></section><div style={{ marginTop: 32 }}><Evidence /></div></>;
}
